"""SC-005: the reference cannot lie about what the code does.

Generation on its own is a convention, and a convention is what somebody skips
on the afternoon they are in a hurry. The test that matters is therefore not
"the generator produces pages" — it is that the check **fails** when the code
moves and the pages do not, and that it fails for a *removed* capability as
well as a changed one.

The removal case is the one a plain content diff misses. A capability deleted
from the catalogue leaves a page nothing regenerates, and a reference sending
somebody to a tool that no longer exists is worse than a reference that is
merely absent.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from tools import check_docs_drift, generate_docs

pytestmark = pytest.mark.contract

REPO_ROOT = Path(__file__).resolve().parents[3]
SITE = REPO_ROOT / "docs" / "site"


def test_the_shipped_reference_is_current() -> None:
    """The same check ``make check-docs`` runs, so a drift fails here too."""
    missing, stale, orphaned = generate_docs.differences(SITE)

    assert (missing, stale, orphaned) == ([], [], []), (
        "docs/site has drifted from the declarations; run `make docs`"
    )


def test_the_drift_check_exits_zero_on_a_current_tree() -> None:
    assert check_docs_drift.main(["--root", str(SITE)]) == 0


def test_every_generated_directory_has_an_index() -> None:
    for directory in generate_docs.GENERATED_DIRECTORIES:
        assert (SITE / directory / "index.md").is_file(), directory


def test_every_generated_page_says_it_is_generated() -> None:
    """A page an operator edits by hand is one that will be silently reverted."""
    for name, page in generate_docs.generated_tree().items():
        assert page.startswith("<!-- Generated by tools/generate_docs.py."), name


# -- the check has to fail, or it proves nothing -------------------------------


def _tree(tmp_path: Path) -> Path:
    """Return a written copy of the generated site under ``tmp_path``."""
    generate_docs.write(tmp_path)
    return tmp_path


def test_a_missing_page_fails_the_check(tmp_path: Path) -> None:
    root = _tree(tmp_path)
    (root / "capabilities" / "index.md").unlink()

    missing, _, _ = generate_docs.differences(root)

    assert "capabilities/index.md" in missing
    assert check_docs_drift.main(["--root", str(root)]) == 1


def test_a_changed_capability_that_was_not_regenerated_fails_the_check(
    tmp_path: Path,
) -> None:
    """SC-005, exactly: change a capability, do not regenerate, fail."""
    root = _tree(tmp_path)
    page = root / "capabilities" / "metrics.md"
    page.write_text(
        page.read_text(encoding="utf-8").replace("`read`", "`write_reversible`", 1),
        encoding="utf-8",
    )

    _, stale, _ = generate_docs.differences(root)

    assert "capabilities/metrics.md" in stale
    assert check_docs_drift.main(["--root", str(root)]) == 1


def test_a_page_for_something_that_no_longer_exists_fails_the_check(
    tmp_path: Path,
) -> None:
    """The removed-capability case. A content diff alone would not see this."""
    root = _tree(tmp_path)
    (root / "capabilities" / "carrier-pigeon.md").write_text(
        "# carrier-pigeon capabilities\n", encoding="utf-8"
    )

    _, _, orphaned = generate_docs.differences(root)

    assert orphaned == ["capabilities/carrier-pigeon.md"]
    assert check_docs_drift.main(["--root", str(root)]) == 1


def test_regenerating_removes_the_page_for_something_that_went(tmp_path: Path) -> None:
    """Generation drops it; the drift check is the second line, not the only one."""
    root = _tree(tmp_path)
    (root / "integrations" / "carrier-pigeon.md").write_text("# gone\n", encoding="utf-8")

    _, removed = generate_docs.write(root)

    assert removed == ["integrations/carrier-pigeon.md"]
    assert not (root / "integrations" / "carrier-pigeon.md").exists()
    assert check_docs_drift.main(["--root", str(root)]) == 0


def test_an_authored_page_beside_the_generated_ones_is_left_alone(
    tmp_path: Path,
) -> None:
    """The generator owns three directories, not the site."""
    root = _tree(tmp_path)
    (root / "quickstart").mkdir(parents=True, exist_ok=True)
    authored = root / "quickstart" / "index.md"
    authored.write_text("# Quickstart\n\nWritten by a person.\n", encoding="utf-8")

    generate_docs.write(root)

    assert authored.read_text(encoding="utf-8") == "# Quickstart\n\nWritten by a person.\n"
    assert check_docs_drift.main(["--root", str(root)]) == 0


def test_writing_twice_changes_nothing_the_second_time(tmp_path: Path) -> None:
    """A generator that rewrote every file would make every commit a whole-tree diff."""
    generate_docs.write(tmp_path)

    written, removed = generate_docs.write(tmp_path)

    assert (written, removed) == ([], [])


# -- the content is the declaration, not a paraphrase --------------------------


def test_a_capability_page_carries_the_side_effect_level_the_gate_enforces() -> None:
    from capabilities.registry.api import catalogue_view
    from capabilities.registry.catalogue import build_registry
    from core.capability.metadata import CapabilityKind

    views = [
        view
        for view in catalogue_view(build_registry())
        if view.kind is CapabilityKind.TOOL and view.domain
    ]
    pages = generate_docs.generated_tree()
    sample = views[0]

    page = pages[f"capabilities/{generate_docs._slug(sample.domain)}.md"]

    assert f"`{sample.name}`" in page
    assert f"`{sample.side_effect_level}`" in page


def test_an_integration_page_carries_the_permissions_verification_probes() -> None:
    from integrations._catalogue.discovery import catalogue

    entries = [entry for entry in catalogue() if entry.profile.permissions]
    assert entries, "the catalogue declares no permissions at all, which cannot be right"

    entry = entries[0]
    page = generate_docs.generated_tree()[
        f"integrations/{generate_docs._slug(entry.category.value)}.md"
    ]

    assert f"`{entry.name}`" in page
    assert f"`{entry.profile.permissions[0].name}`" in page


def test_the_configuration_reference_names_every_setting() -> None:
    from platform.startup.settings import SETTINGS

    whole = "\n".join(
        page
        for name, page in generate_docs.generated_tree().items()
        if name.startswith("configuration/")
    )

    missing = [setting.name for setting in SETTINGS if f"`{setting.name}`" not in whole]

    assert missing == []


def test_the_configuration_reference_marks_a_secret_as_one() -> None:
    whole = "\n".join(
        page
        for name, page in generate_docs.generated_tree().items()
        if name.startswith("configuration/")
    )

    assert "never included in a diagnostic bundle" in whole
