"""Alembic's entry point, shared by the CLI and the running platform.

Two callers, one configuration. The CLI is what a contributor uses to
autogenerate a revision against a scratch database; the platform calls
``postgres.migrations.upgrade_to_head`` at startup and passes its own
connection in through ``config.attributes``. Both land here, so a migration
cannot behave one way when a developer generates it and another way when a
deployment applies it.

The version table is named by a constant rather than left at Alembic's default.
It is a table in the operator's database, and everything else the platform
creates there carries the same prefix.
"""

from __future__ import annotations

import asyncio
import os
from typing import Any, Literal

from alembic import context
from alembic.autogenerate.api import AutogenContext
from sqlalchemy import Connection

from config.constants.persistence import MIGRATION_TABLE_NAME, NINJASRE_DATABASE_URL_ENV
from platform.persistence.postgres import models
from platform.persistence.postgres.crypto import EncryptedSecret
from platform.persistence.postgres.engine import async_url, create_engine

config = context.config
target_metadata = models.Base.metadata


def configured_url() -> str:
    """Return the URL to migrate, from the config or the operator's environment.

    Normalised to the async driver. Alembic's own machinery is synchronous and
    would otherwise reach for psycopg — a second PostgreSQL driver, in the
    dependency tree of every deployment, to serve a command only contributors
    run. One driver is enough.
    """
    return async_url(
        config.get_main_option("sqlalchemy.url") or os.environ.get(NINJASRE_DATABASE_URL_ENV, "")
    )


def run_migrations_offline() -> None:
    """Emit SQL for review rather than applying it.

    Kept for deployments whose schema changes are applied by a DBA rather than
    by the application — common enough in regulated environments to be worth
    the few lines.
    """
    context.configure(
        url=configured_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        version_table=MIGRATION_TABLE_NAME,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def include_object(
    obj: object,
    name: str | None,
    type_: str,
    reflected: bool,
    compare_to: object,
) -> bool:
    """Return whether autogeneration may touch a reflected object.

    It may not touch anything the platform did not declare, and there are two
    kinds of those in this database.

    **Extension-owned tables.** ``ag_catalog`` is on the search path so that
    Apache AGE's operators resolve, which also puts ``ag_graph`` and
    ``ag_label`` in front of Alembic's reflection. Without this filter the very
    first autogenerated revision proposes dropping them — a migration that would
    delete the graph, and one that looks perfectly reasonable in review.

    **The per-generation vector tables.** ``ninjasre_vec_*`` are created at
    runtime by the vector index, with a width that depends on the embedding
    model in use. They are data, not schema. A migration that created them would
    have to guess a dimension, and one that dropped them would delete a corpus.
    """
    return not (type_ == "table" and reflected and name not in target_metadata.tables)


def render_item(type_: str, obj: Any, autogen_context: AutogenContext) -> str | Literal[False]:
    """Render the platform's own column types with an import that resolves.

    Alembic renders an unfamiliar type by its fully-qualified name and does not
    add the import to go with it, which produces a revision that fails at
    ``NameError`` the first time it is applied. Naming the one custom type here
    means the next autogenerated revision is correct rather than correct-looking.
    """
    if type_ == "type" and isinstance(obj, EncryptedSecret):
        autogen_context.imports.add(
            "from platform.persistence.postgres.crypto import EncryptedSecret"
        )
        return "EncryptedSecret()"
    return False


def run_migrations(connection: Connection) -> None:
    """Apply migrations over an existing connection."""
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        version_table=MIGRATION_TABLE_NAME,
        compare_type=True,
        include_object=include_object,
        render_item=render_item,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_on_new_engine() -> None:
    """Connect, migrate, and dispose. The path the Alembic CLI takes."""
    engine = create_engine(configured_url())
    try:
        async with engine.connect() as connection:
            await connection.run_sync(run_migrations)
            await connection.commit()
    finally:
        await engine.dispose()


def run_migrations_online() -> None:
    """Apply migrations, over a caller's connection or one made for the purpose.

    The platform passes its own connection in through ``config.attributes``,
    already inside the advisory lock. The CLI passes nothing and gets an engine
    of its own.
    """
    existing = config.attributes.get("connection", None)
    if isinstance(existing, Connection):
        run_migrations(existing)
        return

    asyncio.run(run_migrations_on_new_engine())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
