"""The credential a fresh deployment gives its operator, and how it stops existing.

A live run of this platform came up perfectly and could not be entered. The
administrator token it printed had been generated by ``secrets.token_urlsafe``
and written into the environment; the running gateway resolved bearer tokens
through the identity store, which had never heard of it. Two sources of truth
about one credential, and the one the operator was given was the wrong one.

So there is one source here, and it is the identity system. The bootstrap
credential is issued by ``TokenService.issue`` against a principal that exists
in the store with a grant that exists in the store, exactly like every other
token this platform serves. It is not a bypass, not a magic header, not a
gateway special case. What makes it a *bootstrap* credential is only that it is
short and narrow:

**Short.** One hour. It is the only credential in the system whose life is
measured in seconds, which is why the token service had to learn a sub-day
lifetime for it rather than the other way round.

**Narrow.** Two permissions: see who you are, and mint a token. The principal
behind it is an owner — it has to be, or the durable credential it establishes
could not be granted anything — but the token itself is ceilinged, so a leaked
bootstrap credential cannot change a configuration or execute a remediation.

**Spent.** Establishing a durable credential revokes it in the same transaction
that issues the replacement, and deletes the file it was delivered in. An hour
is a bound, not a plan.

**Delivered to a file.** The one edge case that decided this: an operator who
closed the terminal before reading the token has not lost their deployment. The
file is written 0600 and is the *copy* — the store is the record. When the two
disagree, the store wins, because a restored backup would otherwise leave a file
nobody can sign in with and no way to tell.
"""

from __future__ import annotations

import json
import os
from collections.abc import Mapping
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

from config.constants.first_run import (
    BOOTSTRAP_AUDIT_ACTION_ESTABLISH,
    BOOTSTRAP_AUDIT_ACTION_ISSUE,
    BOOTSTRAP_AUDIT_RESOURCE_KIND,
    BOOTSTRAP_CREDENTIAL_FILE_MODE,
    BOOTSTRAP_CREDENTIAL_FILENAME,
    BOOTSTRAP_CREDENTIAL_LIFETIME_SECONDS,
    BOOTSTRAP_GRANT_ID,
    BOOTSTRAP_PRINCIPAL_ID,
    BOOTSTRAP_PRINCIPAL_NAME,
    BOOTSTRAP_TOKEN_NAME,
    DEFAULT_DURABLE_CREDENTIAL_NAME,
    DEFAULT_ORGANISATION_ID,
    DEFAULT_ORGANISATION_NAME,
    DEFAULT_STATE_DIR,
    DURABLE_CREDENTIAL_LIFETIME_DAYS,
    NINJASRE_ORGANISATION_ENV,
    NINJASRE_STATE_DIR_ENV,
)
from platform.identity.audit.recorder import AuditContext
from platform.identity.permissions import Permission, Role
from platform.identity.tokens import TokenService
from platform.observability.logging import get_logger
from platform.persistence.ports.audit_repository import ActorKind, AuditEvent
from platform.persistence.ports.identity_repository import PrincipalKind, RoleBinding, User
from platform.persistence.ports.transaction import PersistenceGateway, TenantScope

logger = get_logger(__name__)

#: What the bootstrap token may do, and the whole of it. ``token.manage`` is the
#: purpose; ``investigation.read`` is what ``GET /auth/me`` costs, and a
#: credential that cannot ask who it is cannot complete a sign-in.
BOOTSTRAP_PERMISSIONS: tuple[Permission, ...] = (
    Permission.INVESTIGATION_READ,
    Permission.TOKEN_MANAGE,
)


@dataclass(frozen=True, slots=True)
class BootstrapCredential:
    """The credential an operator is handed, and everything they need about it."""

    secret: str
    token_id: str
    expires_at: datetime
    organisation_id: str

    def live_at(self, now: datetime) -> bool:
        """Return whether this credential is still worth presenting at ``now``."""
        return self.expires_at > now

    def to_record(self) -> dict[str, Any]:
        """Return the JSON form written to the host file."""
        return {
            "secret": self.secret,
            "token_id": self.token_id,
            "expires_at": self.expires_at.isoformat(),
            "organisation_id": self.organisation_id,
        }

    @classmethod
    def from_record(cls, record: Mapping[str, Any]) -> BootstrapCredential:
        """Return the credential a host file describes.

        Raises:
            ValueError: the file is not a credential this release wrote.
        """
        try:
            return cls(
                secret=str(record["secret"]),
                token_id=str(record["token_id"]),
                expires_at=datetime.fromisoformat(str(record["expires_at"])),
                organisation_id=str(record["organisation_id"]),
            )
        except (KeyError, TypeError) as error:
            raise ValueError(f"not a bootstrap credential: {error}") from error


@dataclass(frozen=True, slots=True)
class BringUp:
    """What bring-up established, and whether it had to establish anything."""

    credential: BootstrapCredential
    #: False when a previous bring-up's credential was still live and was reused.
    #: This is the observable half of idempotence: a second run reports that it
    #: issued nothing, rather than quietly replacing a credential somebody has
    #: already written down.
    issued: bool = True

    @property
    def organisation_id(self) -> str:
        """Return the organisation this deployment brought up."""
        return self.credential.organisation_id


def state_dir(environ: Mapping[str, str] | None = None) -> Path:
    """Return where host state that outlives one process is kept."""
    source = environ if environ is not None else os.environ
    return Path(source.get(NINJASRE_STATE_DIR_ENV) or DEFAULT_STATE_DIR)


def credential_path(environ: Mapping[str, str] | None = None) -> Path:
    """Return the file an operator reads the bootstrap credential from."""
    return state_dir(environ) / BOOTSTRAP_CREDENTIAL_FILENAME


def organisation_id(environ: Mapping[str, str] | None = None) -> str:
    """Return the organisation a fresh deployment creates."""
    source = environ if environ is not None else os.environ
    return source.get(NINJASRE_ORGANISATION_ENV) or DEFAULT_ORGANISATION_ID


def read_credential(environ: Mapping[str, str] | None = None) -> BootstrapCredential | None:
    """Return the credential on this host, or ``None`` if there is none to read.

    FR-002's second half. Reading is deliberately tolerant: an unreadable or
    malformed file means there is no credential, not that the deployment is
    broken, because the remedy for both is the same and bring-up will write a
    fresh one.
    """
    path = credential_path(environ)
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    if not isinstance(document, Mapping):
        return None
    try:
        return BootstrapCredential.from_record(document)
    except ValueError:
        return None


def write_credential(
    credential: BootstrapCredential, environ: Mapping[str, str] | None = None
) -> Path:
    """Write ``credential`` to the host file, owner-readable only, and return the path.

    The mode is set on the descriptor rather than after the write. Creating the
    file and then chmod-ing it leaves a window in which a live credential is
    world-readable, and the window is exactly as long as the scheduler decides.
    """
    path = credential_path(environ)
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor = os.open(
        path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, BOOTSTRAP_CREDENTIAL_FILE_MODE
    )
    with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
        json.dump(credential.to_record(), handle, indent=2)
    os.chmod(path, BOOTSTRAP_CREDENTIAL_FILE_MODE)
    return path


def forget_credential(environ: Mapping[str, str] | None = None) -> None:
    """Remove the host file. Idempotent; a missing file is the desired state."""
    credential_path(environ).unlink(missing_ok=True)


def announcement(credential: BootstrapCredential, *, path: Path) -> str:
    """Return the block printed once at first start.

    Printed rather than logged. A log line goes through the structured logger,
    the structured logger goes wherever the operator pointed it, and FR-004 says
    the bootstrap credential appears in no log. So it is written to the terminal
    and to one file, and nowhere else.
    """
    rule = "=" * 72
    return "\n".join(
        [
            rule,
            "  NinjaSRE is up. Sign in with this credential:",
            "",
            f"    {credential.secret}",
            "",
            f"  It expires at {credential.expires_at.isoformat()} and can do exactly two",
            "  things: tell you who you are, and create your own account. Do that first;",
            "  this credential is revoked the moment you have.",
            "",
            f"  If you lose this screen it is readable again at {path}",
            rule,
        ]
    )


# --- Bringing a deployment up ---------------------------------------------------


async def bring_up(
    gateway: PersistenceGateway,
    tokens: TokenService,
    *,
    environ: Mapping[str, str] | None = None,
    now: datetime | None = None,
) -> BringUp:
    """Make this deployment enterable, and return the credential that enters it.

    Idempotent (FR-005). Running it a second time creates no second
    organisation, no second grant, and no second credential: if the one on the
    host is still live and the store still holds it, that one is returned
    unchanged and ``issued`` is ``False``.

    Nothing here resets or wipes anything. The only destructive step in the whole
    first-run path is the revocation that spends the credential, and that happens
    in ``establish_durable_credential`` where somebody asked for it.
    """
    instant = now or datetime.now(UTC)
    org_id = organisation_id(environ)

    await _ensure_organisation(gateway, org_id)
    await _ensure_bootstrap_principal(gateway, org_id)

    existing = read_credential(environ)
    reusable = (
        existing is not None
        and existing.organisation_id == org_id
        and existing.live_at(instant)
        and await _token_is_live(gateway, org_id, existing.token_id, instant)
    )
    if reusable and existing is not None:
        logger.info("bootstrap.credential_reused", organisation_id=org_id)
        return BringUp(credential=existing, issued=False)

    credential = await _issue(gateway, tokens, org_id=org_id)
    write_credential(credential, environ)
    logger.info(
        "bootstrap.credential_issued",
        organisation_id=org_id,
        token_id=credential.token_id,
        expires_at=credential.expires_at.isoformat(),
    )
    return BringUp(credential=credential, issued=True)


async def establish_durable_credential(
    gateway: PersistenceGateway,
    tokens: TokenService,
    *,
    bootstrap: BootstrapCredential,
    user_id: str,
    email: str,
    display_name: str,
    name: str = DEFAULT_DURABLE_CREDENTIAL_NAME,
    environ: Mapping[str, str] | None = None,
) -> DurableCredential:
    """Exchange the bootstrap credential for one that lasts, and spend it.

    The bootstrap credential is authenticated first, through the same path a
    request takes. That is what makes a second exchange with the same credential
    fail rather than mint a second owner — and it is why this raises
    ``TokenRejected`` rather than returning a refusal: the caller presented a
    credential that is no longer one.

    Raises:
        TokenRejected: the bootstrap credential is expired, revoked, or unknown.
    """
    await tokens.authenticate(bootstrap.secret)

    scope = TenantScope(org_id=bootstrap.organisation_id)
    async with gateway.begin(scope) as uow:
        await uow.identity.upsert_user(
            User(
                user_id=user_id,
                email=email,
                display_name=display_name,
                kind=PrincipalKind.USER,
            )
        )
        await uow.identity.upsert_role_binding(
            RoleBinding(
                binding_id=f"{user_id}-owner",
                user_id=user_id,
                role=Role.OWNER.value,
                node_id=None,
            )
        )

    issued = await tokens.issue(
        scope,
        AuditContext(actor_kind=ActorKind.USER, actor_id=user_id),
        user_id=user_id,
        name=name,
        description="Established from the bootstrap credential at first run.",
        lifetime_days=DURABLE_CREDENTIAL_LIFETIME_DAYS,
    )

    # Revoked after the replacement exists, never before. The other order leaves
    # a window where the operator holds nothing at all, and the window is exactly
    # as long as whatever goes wrong next.
    await tokens.revoke(
        scope,
        AuditContext(actor_kind=ActorKind.USER, actor_id=user_id),
        bootstrap.token_id,
    )
    forget_credential(environ)

    await _record(
        gateway,
        scope,
        action=BOOTSTRAP_AUDIT_ACTION_ESTABLISH,
        actor_id=user_id,
        resource_id=issued.token.token_id,
        detail={"replaced": bootstrap.token_id, "principal": user_id},
    )
    logger.info("bootstrap.durable_credential_established", user_id=user_id)

    expires_at = issued.token.expires_at or datetime.now(UTC)
    return DurableCredential(
        secret=issued.secret,
        token_id=issued.token.token_id,
        expires_at=expires_at,
        user_id=user_id,
    )


@dataclass(frozen=True, slots=True)
class DurableCredential:
    """What the operator ends up holding: their own token, on their own account."""

    secret: str
    token_id: str
    expires_at: datetime
    user_id: str

    def to_record(self) -> dict[str, Any]:
        """Return the JSON form a surface returns exactly once."""
        return {
            "secret": self.secret,
            "token_id": self.token_id,
            "expires_at": self.expires_at.isoformat(),
            "user_id": self.user_id,
        }


# --- The pieces bring-up assembles ----------------------------------------------


async def _ensure_organisation(gateway: PersistenceGateway, org_id: str) -> None:
    """Create the organisation if it is not there. Never touch it if it is."""
    async with gateway.begin_system() as system:
        if await system.orgs.get_organisation(org_id) is not None:
            return
        name = DEFAULT_ORGANISATION_NAME if org_id == DEFAULT_ORGANISATION_ID else org_id
        await system.orgs.create_organisation(org_id, name)
    logger.info("bootstrap.organisation_created", organisation_id=org_id)


async def _ensure_bootstrap_principal(gateway: PersistenceGateway, org_id: str) -> None:
    """Create the principal and its owner grant, idempotently.

    ``upsert`` on both, so the second bring-up writes the same row rather than a
    second one — which is what FR-005 means by "duplicate nothing".
    """
    async with gateway.begin(TenantScope(org_id=org_id)) as uow:
        await uow.identity.upsert_user(
            User(
                user_id=BOOTSTRAP_PRINCIPAL_ID,
                email="",
                display_name=BOOTSTRAP_PRINCIPAL_NAME,
                kind=PrincipalKind.SERVICE_ACCOUNT,
            )
        )
        await uow.identity.upsert_role_binding(
            RoleBinding(
                binding_id=BOOTSTRAP_GRANT_ID,
                user_id=BOOTSTRAP_PRINCIPAL_ID,
                role=Role.OWNER.value,
                node_id=None,
            )
        )


async def _issue(
    gateway: PersistenceGateway, tokens: TokenService, *, org_id: str
) -> BootstrapCredential:
    """Issue a fresh bootstrap credential through the identity system."""
    scope = TenantScope(org_id=org_id)
    context = AuditContext(actor_kind=ActorKind.SYSTEM, actor_id=BOOTSTRAP_PRINCIPAL_ID)
    issued = await tokens.issue(
        scope,
        context,
        user_id=BOOTSTRAP_PRINCIPAL_ID,
        name=BOOTSTRAP_TOKEN_NAME,
        permissions=BOOTSTRAP_PERMISSIONS,
        description="First-run credential. Establishes a durable one, then expires.",
        lifetime=timedelta(seconds=BOOTSTRAP_CREDENTIAL_LIFETIME_SECONDS),
    )
    expires_at = issued.token.expires_at or datetime.now(UTC) + timedelta(
        seconds=BOOTSTRAP_CREDENTIAL_LIFETIME_SECONDS
    )

    await _record(
        gateway,
        scope,
        action=BOOTSTRAP_AUDIT_ACTION_ISSUE,
        actor_id=BOOTSTRAP_PRINCIPAL_ID,
        resource_id=issued.token.token_id,
        # No secret. The audit trail records that a credential was issued and
        # when it dies, which is what a reviewer needs; FR-004 says the value
        # itself appears in no audit export.
        detail={"expires_at": expires_at.isoformat()},
    )
    return BootstrapCredential(
        secret=issued.secret,
        token_id=issued.token.token_id,
        expires_at=expires_at,
        organisation_id=org_id,
    )


async def _token_is_live(
    gateway: PersistenceGateway, org_id: str, token_id: str, now: datetime
) -> bool:
    """Return whether the store still holds ``token_id`` as usable."""
    async with gateway.begin(TenantScope(org_id=org_id)) as uow:
        for token in await uow.identity.tokens_for_user(BOOTSTRAP_PRINCIPAL_ID):
            if token.token_id != token_id:
                continue
            if token.revoked_at is not None:
                return False
            return token.expires_at is None or token.expires_at > now
    return False


async def _record(
    gateway: PersistenceGateway,
    scope: TenantScope,
    *,
    action: str,
    actor_id: str,
    resource_id: str,
    detail: Mapping[str, Any],
) -> None:
    """Append one audit event for a first-run step."""
    async with gateway.begin(scope) as uow:
        await uow.audit.append(
            AuditEvent(
                event_id=f"{action}-{resource_id}",
                occurred_at=datetime.now(UTC),
                actor_kind=ActorKind.SYSTEM,
                actor_id=actor_id,
                action=action,
                resource_kind=BOOTSTRAP_AUDIT_RESOURCE_KIND,
                resource_id=resource_id,
                detail=dict(detail),
            )
        )


__all__ = [
    "BOOTSTRAP_PERMISSIONS",
    "BootstrapCredential",
    "BringUp",
    "DurableCredential",
    "announcement",
    "bring_up",
    "credential_path",
    "establish_durable_credential",
    "forget_credential",
    "organisation_id",
    "read_credential",
    "state_dir",
    "write_credential",
]
