"""Generate the documentation site's reference sections from the code itself.

Three sections are generated, and the reason is the same for all three: they
describe what the code *is*, and a hand-written description of that is wrong
within two releases. Not gradually — immediately, at the first capability whose
side-effect level changes, the first integration whose permission list grows,
the first setting somebody adds. A reference that says a tool is read-only when
it is not is worse than no reference, because somebody acts on it.

- **Capabilities** — from the same declarations the scorer and the approval gate
  read, one page per domain.
- **Integrations** — from the same catalogue the console reads, one page per
  category.
- **Configuration** — from the settings catalogue ``.env.example`` is rendered
  from, one page per section.

The authored sections — quickstart, deployment, security, evaluation,
contributing — are not touched. They describe decisions and threats, which is
what a person is for.

``tools/check_docs_drift.py`` regenerates and compares; a file under a generated
directory that this generator did not produce is a stale reference and fails the
same check. That is what handles a removed capability: the page goes, and the
build notices if the deletion did not reach the tree.

Usage::

    python -m tools.generate_docs [--root docs/site] [--check]

Run as a module from the repository root: it imports the first-party packages,
and ``platform/`` only wins its name over the stdlib module when the repository
root leads ``sys.path``.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

from capabilities.registry.api import CapabilityView, catalogue_view, summary
from capabilities.registry.catalogue import build_registry
from core.capability.metadata import CapabilityKind
from integrations._catalogue.discovery import catalogue
from integrations._catalogue.entry import CatalogueEntry
from platform.startup.settings import SETTINGS, Setting, sections
from tools.generate_capability_docs import _render_skill, _render_tool
from tools.generate_integration_docs import _render_entry

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ROOT = REPO_ROOT / "docs" / "site"

#: The three directories this generator owns entirely. Everything inside one is
#: produced here, which is what lets the drift check treat an unexpected file as
#: a stale reference rather than as somebody's note.
GENERATED_DIRECTORIES: tuple[str, ...] = ("capabilities", "integrations", "configuration")

_BANNER = (
    "<!-- Generated by tools/generate_docs.py. Do not edit by hand: edit the "
    "declaration and regenerate, or `make check-docs` will fail and this file "
    "will be the one that is wrong. -->"
)


def _slug(name: str) -> str:
    """Return ``name`` as a file name: lower case, no spaces, no separators."""
    return "".join(
        character if character.isalnum() else "-" for character in name.strip().lower()
    ).strip("-")


def _page(title: str, intro: str, body: Sequence[str]) -> str:
    """Return one whole generated page."""
    lines = [_BANNER, "", f"# {title}", "", intro, "", *body]
    return "\n".join(lines).rstrip("\n") + "\n"


# -- capabilities ---------------------------------------------------------------


def capability_pages(views: Sequence[CapabilityView]) -> dict[str, str]:
    """Return one page per capability domain, plus the index that lists them."""
    by_domain: dict[str, list[CapabilityView]] = {}
    for view in views:
        by_domain.setdefault(view.domain or "uncategorised", []).append(view)

    pages: dict[str, str] = {}
    for domain, found in sorted(by_domain.items()):
        skills = [view for view in found if view.kind is CapabilityKind.SKILL]
        tools = [view for view in found if view.kind is CapabilityKind.TOOL]
        body: list[str] = []
        if skills:
            body.extend(["## Skills", ""])
            for view in sorted(skills, key=lambda entry: entry.name):
                body.extend(_render_skill(view))
        if tools:
            body.extend(["## Tools", ""])
            for view in sorted(tools, key=lambda entry: entry.name):
                body.extend(_render_tool(view))
        pages[f"{_slug(domain)}.md"] = _page(
            f"{domain} capabilities",
            f"{len(tools)} tools and {len(skills)} skills the agent may call in this domain. "
            f"Every entry is generated from the declaration the approval gate reads, so the "
            f"side-effect level below is the one that is actually enforced.",
            body,
        )

    counts = summary(views)
    index = [
        "| Domain | Tools | Skills |",
        "|---|---|---|",
        *(
            f"| [{domain}]({_slug(domain)}.md) | "
            f"{sum(1 for view in found if view.kind is CapabilityKind.TOOL)} | "
            f"{sum(1 for view in found if view.kind is CapabilityKind.SKILL)} |"
            for domain, found in sorted(by_domain.items())
        ),
    ]
    pages["index.md"] = _page(
        "Capability reference",
        f"{counts['tools']} tools and {counts['skills']} skills, "
        f"{counts['approval_gated']} of them approval-gated. A capability with no "
        f"declared side-effect level is treated as a write and gated accordingly, "
        f"so an omission is safe rather than silent.",
        index,
    )
    return pages


# -- integrations ---------------------------------------------------------------


def integration_pages(entries: Sequence[CatalogueEntry]) -> dict[str, str]:
    """Return one page per integration category, plus the index that lists them."""
    by_category: dict[str, list[CatalogueEntry]] = {}
    for entry in entries:
        by_category.setdefault(entry.category.value, []).append(entry)

    pages: dict[str, str] = {}
    for category, found in sorted(by_category.items()):
        body: list[str] = []
        for entry in sorted(found, key=lambda item: item.name):
            body.extend(_render_entry(entry))
        pages[f"{_slug(category)}.md"] = _page(
            f"{category} integrations",
            f"{len(found)} vendor(s). Every one ships the same seven artefacts and the "
            f"build fails naming both the integration and the artefact when one is "
            f"missing — which is what makes full parity a property rather than a claim. "
            f"The permission tables below are the ones verification actually probes.",
            body,
        )

    index = [
        "| Category | Integrations |",
        "|---|---|",
        *(
            f"| [{category}]({_slug(category)}.md) | {len(found)} |"
            for category, found in sorted(by_category.items())
        ),
    ]
    pages["index.md"] = _page(
        "Integration catalogue",
        f"{len(entries)} integrations, grouped by what they are for. Credentials never "
        f"reach the agent: an integration client carries a scoped handle and the "
        f"credential proxy injects the secret at the network edge.",
        index,
    )
    return pages


# -- configuration ---------------------------------------------------------------


def _setting_block(setting: Setting) -> list[str]:
    """Return the lines documenting one setting."""
    default = f"`{setting.default}`" if setting.default else "none"
    lines = [
        f"### `{setting.name}`",
        "",
        setting.effect,
        "",
        f"- **Required:** {'yes' if setting.required else 'no'}",
        f"- **Default:** {default}",
    ]
    if setting.secret:
        lines.append(
            "- **Secret:** yes — never printed, never included in a diagnostic bundle, "
            "and never passed to the agent."
        )
    lines.append("")
    return lines


def configuration_pages(settings: Sequence[Setting]) -> dict[str, str]:
    """Return one page per settings section, plus the index that lists them."""
    pages: dict[str, str] = {}
    for section in sections():
        found = [setting for setting in settings if setting.section == section]
        body: list[str] = []
        for setting in found:
            body.extend(_setting_block(setting))
        pages[f"{_slug(section)}.md"] = _page(
            section,
            f"{len(found)} setting(s). Every one is read from the environment; there is "
            f"no configuration file a deployment needs before it can start.",
            body,
        )

    required = [setting for setting in settings if setting.required]
    index = [
        "## The minimum",
        "",
        "A deployment needs exactly these:",
        "",
        *(f"- `{setting.name}` — {setting.effect}" for setting in required),
        "",
        "Everything else has a working default.",
        "",
        "## Every section",
        "",
        "| Section | Settings |",
        "|---|---|",
        *(
            f"| [{section}]({_slug(section)}.md) | "
            f"{sum(1 for setting in settings if setting.section == section)} |"
            for section in sections()
        ),
    ]
    pages["index.md"] = _page(
        "Configuration reference",
        f"{len(settings)} settings, generated from the catalogue "
        f"`deploy/compose/.env.example` is rendered from — so this page and that file "
        f"cannot disagree.",
        index,
    )
    return pages


# -- the whole tree --------------------------------------------------------------


def generated_tree() -> dict[str, str]:
    """Return every generated page, keyed by its path relative to the site root."""
    tree: dict[str, str] = {}
    for name, page in capability_pages(catalogue_view(build_registry())).items():
        tree[f"capabilities/{name}"] = page
    for name, page in integration_pages(catalogue()).items():
        tree[f"integrations/{name}"] = page
    for name, page in configuration_pages(SETTINGS).items():
        tree[f"configuration/{name}"] = page
    return tree


def written_tree(root: Path) -> dict[str, str]:
    """Return what is currently on disk under the generated directories."""
    found: dict[str, str] = {}
    for directory in GENERATED_DIRECTORIES:
        base = root / directory
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*.md")):
            found[path.relative_to(root).as_posix()] = path.read_text(encoding="utf-8")
    return found


def differences(root: Path) -> tuple[list[str], list[str], list[str]]:
    """Return the pages that are missing, stale, and orphaned, in that order.

    An orphan is the case a content diff alone would miss: a capability removed
    from the catalogue leaves a page nothing regenerates, and a reference to
    something that no longer exists is exactly what this whole mechanism is for.
    """
    expected = generated_tree()
    actual = written_tree(root)
    missing = sorted(set(expected) - set(actual))
    orphaned = sorted(set(actual) - set(expected))
    stale = sorted(name for name in set(expected) & set(actual) if expected[name] != actual[name])
    return missing, stale, orphaned


def write(root: Path) -> tuple[list[str], list[str]]:
    """Write the generated tree under ``root``, returning what was written and removed."""
    expected = generated_tree()
    written: list[str] = []
    for name, page in sorted(expected.items()):
        path = root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text(encoding="utf-8") != page:
            path.write_text(page, encoding="utf-8", newline="\n")
            written.append(name)

    removed: list[str] = []
    for name in sorted(set(written_tree(root)) - set(expected)):
        (root / name).unlink()
        removed.append(name)
    return written, removed


def main(argv: Sequence[str] | None = None) -> int:
    """Write the generated reference, or report that it is out of date."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when the tree has drifted from the declarations",
    )
    arguments = parser.parse_args(argv)
    root: Path = arguments.root

    if arguments.check:
        missing, stale, orphaned = differences(root)
        if not (missing or stale or orphaned):
            return 0
        for name in missing:
            print(f"missing: {name}", file=sys.stderr)  # noqa: T201 — talking to a person
        for name in stale:
            print(f"out of date: {name}", file=sys.stderr)  # noqa: T201
        for name in orphaned:
            print(  # noqa: T201
                f"stale reference: {name} documents something that no longer exists",
                file=sys.stderr,
            )
        print(  # noqa: T201
            "\nRun `make docs` to regenerate. These pages are produced from the "
            "declarations; editing them by hand is how the reference comes to disagree "
            "with the behaviour.",
            file=sys.stderr,
        )
        return 1

    written, removed = write(root)
    print(f"wrote {len(written)} page(s), removed {len(removed)}")  # noqa: T201
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
