"""Create an integration that is complete on the first commit (FR-017).

An integration has seven artefacts, and five of them are boring. The schema is
four fields, the client is a base class and two methods, the verifier is a probe
and a permission list, the documentation has three headings, and the scenario is
a scripted response. Written by hand, every one of them is a chance to write it
slightly differently from every other one — and the two that are not
boring, the methodology and the permission list, are the ones a contributor runs
out of energy for after writing the five that were.

So this writes all seven, none of them empty, and edits nothing. That second
half is what makes a catalogue of any size
addable one package at a time: discovery walks the tree, so there is no registry
to append to and no merge conflict on every pull request.

**What it deliberately does not decide.** The side-effect level has no default,
structurally, and this writes ``READ`` with the reasoning beside it rather than
silently. The permission list is a stub, because a permission somebody guessed
is worse than one nobody wrote — a verifier that probes the wrong scope reports
success for a credential that cannot do the job. Both are printed as follow-up
work, because a template with a marked field gets filled in and a field that was
never mentioned does not.

Usage::

    python tools/scaffold_integration.py <vendor> --domain <domain> [--dry-run]
"""

from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

#: A vendor name becomes a package name, a credential key, and the prefix of
#: every tool name the model emits as a symbol. Lowercase, letters, digits, and
#: underscores.
INTEGRATION_NAME_PATTERN = re.compile(r"^[a-z][a-z0-9_]*$")

#: The token every domain template uses for the vendor it is instantiated for.
PLACEHOLDER = "VENDOR"

#: Which category enum member a domain name maps to, as written in generated
#: source. Derived from the domain rather than declared, because the template
#: directories are named for the category values — see ``template_for``.
_CATEGORY_MEMBERS: dict[str, str] = {
    "logstore": "LOG_STORE",
    "metrics": "METRICS_STORE",
    "tracing": "TRACING",
    "cloud_control_plane": "CLOUD_CONTROL_PLANE",
    "database": "DATABASE",
    "vcs": "VERSION_CONTROL",
    "cicd": "CI_CD",
    "ticketing": "TICKETING",
    "incident": "INCIDENT_MANAGEMENT",
    "communication": "COMMUNICATION",
    "data_platform": "DATA_PLATFORM",
}

_TEMPLATE_ROOT_PARTS = ("capabilities", "skills", "_templates")
_SKILL_ROOT_PARTS = ("capabilities", "skills")
_SCENARIO_ROOT_PARTS = ("tests", "synthetic", "integration_scenarios")

#: Written into the head of every generated module. Not decoration: a reader
#: who knows a file was generated knows which parts are the framework's shape
#: and which parts are somebody's decision about this vendor.
_PROVENANCE = (
    "Generated by tools/scaffold_integration.py. The shape is the framework's; "
    "everything the vendor decides is marked TODO."
)


class ScaffoldError(Exception):
    """The integration cannot be created as asked."""


@dataclass(frozen=True)
class Plan:
    """Where a scaffolded integration's seven artefacts go."""

    package: Path
    schema: Path
    verifier: Path
    client: Path
    tools_package: Path
    tool_module: Path
    docs: Path
    skill: Path
    scenario: Path

    def paths(self) -> tuple[Path, ...]:
        """Return every path this plan writes, in the order it writes them."""
        return (
            self.package / "__init__.py",
            self.schema,
            self.client,
            self.verifier,
            self.tools_package / "__init__.py",
            self.tool_module,
            self.docs,
            self.skill,
            self.scenario,
        )


def template_for(domain: str) -> str:
    """Return the template directory a domain's skill starts from.

    Identity, and that is the design: the template directories are named for the
    catalogue's category values, so there is no mapping table to keep in step
    with the enum. A domain with no directory is caught by ``validate``.
    """
    return domain


def domains(repo_root: Path) -> tuple[str, ...]:
    """Return every domain a skill can be started from, in name order."""
    root = repo_root.joinpath(*_TEMPLATE_ROOT_PARTS)
    if not root.is_dir():
        return ()
    return tuple(sorted(path.parent.name for path in root.rglob("SKILL.md")))


def plan_for(repo_root: Path, integration: str) -> Plan:
    """Return where the seven artefacts go for ``integration``."""
    package = repo_root / "integrations" / integration
    return Plan(
        package=package,
        schema=package / "schema.py",
        verifier=package / "verifier.py",
        client=package / "client.py",
        tools_package=package / "tools",
        tool_module=package / "tools" / "log_statistics.py",
        docs=package / "docs.md",
        skill=repo_root.joinpath(*_SKILL_ROOT_PARTS) / integration / "SKILL.md",
        scenario=repo_root.joinpath(*_SCENARIO_ROOT_PARTS) / f"{integration}.py",
    )


def validate(repo_root: Path, integration: str, domain: str) -> Plan:
    """Return the plan, or explain why the integration cannot be created."""
    if integration.startswith("_"):
        raise ScaffoldError(
            f"{integration!r} begins with an underscore, which marks a framework package "
            f"under integrations/ — discovery skips those, so the integration would be "
            f"invisible the moment it landed"
        )
    if not INTEGRATION_NAME_PATTERN.match(integration):
        raise ScaffoldError(
            f"{integration!r} is not a usable integration name: lowercase, starting with a "
            f"letter, letters, digits, and underscores only. It becomes a package name and "
            f"the prefix of every tool name the model emits as a symbol."
        )

    available = domains(repo_root)
    if domain not in available:
        raise ScaffoldError(
            f"{domain!r} is not a domain with a methodology template. Available: "
            f"{', '.join(available) if available else 'none'}"
        )

    plan = plan_for(repo_root, integration)
    for path in plan.paths():
        if path.exists():
            raise ScaffoldError(f"{path.relative_to(repo_root)} already exists")
    return plan


# --- What each artefact starts as --------------------------------------------


PACKAGE_TEMPLATE = '''"""{title}: TODO — one line on what an investigation asks it.

{provenance}

Two declarations, and discovery walks for both. ``DESCRIPTOR`` is the credential
half — what a credential is made of, which hosts it may reach, how the secret
enters a request, and how to check that it works. ``PROFILE`` is the operational
half — what class of system this is, where it can be reached, what permissions
its capabilities need, and how its endpoints page.
"""

from __future__ import annotations

from typing import Final

from integrations._catalogue.entry import IntegrationCategory, IntegrationProfile
from integrations.{integration}.client import PAGINATION, {client_class}
from integrations.{integration}.schema import HOSTS, INTEGRATION, REGIONS, RULE, SCHEMA
from integrations.{integration}.verifier import PERMISSIONS, {verifier_class}
from platform.credentials.descriptor import IntegrationDescriptor, SdkStrategy

DESCRIPTOR: Final = IntegrationDescriptor(
    name=INTEGRATION,
    schema=SCHEMA,
    rule=RULE,
    verifier={verifier_class}(),
    client_class={client_class},
    # TODO: choose the row of the SDK table this vendor sits on, and say why.
    # DIRECT_CLIENT when the SDK is thin over REST; ROUTED_SDK when it accepts a
    # custom transport; PROXY_SIGNED when it signs in-process. There is no
    # fourth option: a library that insists on loading its own key is replaced.
    sdk_strategy=SdkStrategy.DIRECT_CLIENT,
    strategy_note=(
        "TODO: why this row rather than the others, in enough detail that somebody "
        "reviewing it a year from now can tell whether the reasoning still holds. A "
        "one-line rationale is not a decision anybody can review."
    ),
)

PROFILE: Final = IntegrationProfile(
    integration=INTEGRATION,
    category=IntegrationCategory.{category},
    summary="TODO: one line. The console and the generated documentation both read this.",
    regions=REGIONS,
    permissions=PERMISSIONS,
    pagination=PAGINATION,
)

__all__ = [
    "DESCRIPTOR",
    "HOSTS",
    "INTEGRATION",
    "PAGINATION",
    "PERMISSIONS",
    "PROFILE",
    "REGIONS",
    "RULE",
    "SCHEMA",
    "{client_class}",
    "{verifier_class}",
]
'''

SCHEMA_TEMPLATE = '''"""{title}'s credential shape, hosts, and how its secret enters a request.

{provenance}

Three things are declared here and each has a failure it prevents. The schema is
what an operator is prompted for, and a field they were never asked for is a
credential that half works. The region map is the egress allow-list — one tuple,
not two, because two would drift. The injection rule is how the secret is added
at the network edge, and every field it reads has to be one the schema declares
or the request goes out unauthenticated.
"""

from __future__ import annotations

from typing import Final

from integrations._base.regions import RegionMap
from integrations._base.schema import bearer_token_schema, public
from platform.credentials.proxy.injection import BearerTokenInjection, InjectionRule

INTEGRATION: Final = "{integration}"

#: TODO: every host this vendor serves its API from, one region per entry.
#: Exact names, no wildcards: ``*.vendor.com`` is one delegated zone away from
#: permitting a host nobody approved. Use ``RegionMap.from_template`` instead
#: when the host names are mechanical.
REGIONS: Final = RegionMap.single(INTEGRATION, host="api.{integration}.example")

#: The egress allow-list, which is the region map rather than a second tuple.
HOSTS: Final[tuple[str, ...]] = REGIONS.hosts()

#: TODO: the fields this vendor's credential actually has. ``bearer_token_schema``
#: covers the common case; ``api_key_schema``, ``basic_auth_schema``, and
#: ``key_pair_schema`` cover the rest. Add a ``pattern`` only where the vendor's
#: format is genuinely fixed — a nearly-right pattern rejects a valid newer key
#: and the operator has no way to override it.
SCHEMA: Final = bearer_token_schema(
    INTEGRATION,
    description="TODO: where an operator gets this token, named as the vendor names it.",
    extra=(public("region", "TODO: which regional deployment this organisation is on."),),
)

RULE: Final = InjectionRule(
    integration=INTEGRATION,
    hosts=HOSTS,
    injections=(BearerTokenInjection(field="token"),),
)


def base_url(region: str = "") -> str:
    """Return the API base URL for a region, or for the default one."""
    return REGIONS.base_url(region)


__all__ = [
    "HOSTS",
    "INTEGRATION",
    "REGIONS",
    "RULE",
    "SCHEMA",
    "base_url",
]
'''

CLIENT_TEMPLATE = '''"""{title}'s API, over the proxy, holding no credential.

{provenance}

This file is the whole integration as far as the vendor is concerned — paths,
query grammar, and pagination — and every line of it would be the same if the
vendor's authentication changed tomorrow, because the authentication is not in
it. There is no constructor parameter for a credential and no attribute to hold
one; ``IntegrationClient`` is shaped so the wrong thing is unspellable.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Final

from integrations._base.client import ClientResponse, IntegrationClient
from integrations._base.pagination import (
    MAX_PAGES_PER_CALL,
    EndpointPagination,
    Page,
    PaginationStyle,
    Pages,
    walk,
)
from integrations._base.retry import RetryPolicy
from integrations._base.transport import ProxyTransport, RequestContext
from integrations.{integration}.schema import INTEGRATION, base_url

#: TODO: the vendor's own paths.
SEARCH_PATH: Final = "/api/v1/search"
PING_PATH: Final = "/api/v1/status"

#: TODO: the vendor's own per-page ceiling. Asking for more is answered with
#: this anyway, so requesting it makes the page count predictable.
MAX_PAGE_SIZE: Final = 100

#: How each paginated endpoint asks for the page after the one it read (FR-005).
#: TODO: check the vendor's documentation for the word it uses. ``CURSOR`` and
#: ``PAGE_TOKEN`` both terminate on an absent token; ``OFFSET`` terminates on a
#: short page and must declare its page size.
PAGINATION: Final[tuple[EndpointPagination, ...]] = (
    EndpointPagination(
        endpoint="search",
        style=PaginationStyle.CURSOR,
        parameter="cursor",
        page_size_parameter="limit",
        page_size=MAX_PAGE_SIZE,
    ),
)


class {client_class}(IntegrationClient):
    """{title}, reached through the credential proxy."""

    integration = INTEGRATION

    __slots__ = ("_region",)

    def __init__(
        self,
        *,
        transport: ProxyTransport,
        context: RequestContext,
        region: str = "",
        retry: RetryPolicy | None = None,
    ) -> None:
        super().__init__(
            transport=transport,
            context=context,
            base_url=base_url(region),
            retry=retry,
        )
        self._region = region

    @property
    def region(self) -> str:
        """Return the region this client reads from."""
        return self._region

    async def search(
        self,
        query: str,
        *,
        start: str,
        end: str,
        limit: int = MAX_PAGE_SIZE,
        max_pages: int = MAX_PAGES_PER_CALL,
    ) -> Pages[dict[str, Any]]:
        """Return what matches ``query`` in the window, bounded.

        TODO: replace with the vendor's own request shape. The result carries
        ``truncated``, and a capability that drops it is reporting "no more
        matches" when what happened was "we stopped looking".
        """

        async def fetch(parameters: Mapping[str, str]) -> Page[dict[str, Any]]:
            asked = {{"q": query, "from": start, "to": end, **parameters}}
            answer = (await self.get(SEARCH_PATH, params=asked)).json()
            cursor = answer.get("next_cursor")
            return Page(items=tuple(answer.get("results", ())), cursor=str(cursor) if cursor else None)

        return await walk(PAGINATION[0], fetch, max_pages=max_pages, max_items=limit)

    async def ping(self) -> ClientResponse:
        """Make the cheapest authenticated call this vendor offers.

        Used by the verifier, and the one method every client must have: it is
        what proves a credential works without spending quota or reading data.
        """
        return await self.get(PING_PATH)


__all__ = [
    "MAX_PAGE_SIZE",
    "PAGINATION",
    "PING_PATH",
    "SEARCH_PATH",
    "{client_class}",
]
'''

VERIFIER_TEMPLATE = '''"""Proves a {title} credential works, and proves what it is allowed to do.

{provenance}

Two questions, and the second is the one that costs an hour when it is skipped.
A credential that authenticates can still be scoped without the permission one
capability needs, and that failure surfaces during an incident as a tool error
with no sign that it was knowable at setup time.

So connectivity is one cheap call and each permission is its own cheap call, and
the report names the permission rather than the failure (FR-009, FR-010).
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final

from integrations._base.errors import IntegrationError, IntegrationErrorReason
from integrations._base.transport import ProxyTransport, RequestContext
from integrations._verification.framework import Connectivity
from integrations._verification.permissions import (
    PermissionProbe,
    RequiredPermission,
    client_probe,
)
from integrations.{integration}.client import {client_class}
from integrations.{integration}.schema import INTEGRATION
from platform.credentials.verification import VerificationResult

#: What each failure means for this vendor, in the operator's terms. "401" and
#: "403" are different problems with different fixes, and an operator told only
#: that verification failed will check the wrong thing first.
_ADVICE: dict[IntegrationErrorReason, str] = {{
    IntegrationErrorReason.UNAUTHENTICATED: (
        "TODO: what the operator does when this vendor rejects the credential, named "
        "as the vendor's own console names it."
    ),
    IntegrationErrorReason.FORBIDDEN: (
        "TODO: what the operator does when the credential is valid and the scope is not."
    ),
    IntegrationErrorReason.CREDENTIAL_UNAVAILABLE: (
        "No {title} credential is configured for this team."
    ),
    IntegrationErrorReason.REFUSED: (
        "The proxy refused the call before it left: this host is not in the "
        "integration's declared allow-list."
    ),
    IntegrationErrorReason.PROXY_UNAVAILABLE: (
        "The credential proxy did not answer. Authenticated calls have no path around it."
    ),
}}

#: TODO: one entry per permission this integration's capabilities actually need,
#: named as the vendor names it. A guessed permission is worse than a missing
#: one: the verifier reports success for a credential that cannot do the job.
SEARCH_PERMISSION: Final = RequiredPermission(
    name="TODO:vendor-permission-name",
    grants="TODO: what it lets this integration do, in the operator's words",
    capabilities=("{integration}_log_statistics",),
    where="TODO: where in this vendor's console the permission is granted",
)

PERMISSIONS: Final[tuple[RequiredPermission, ...]] = (SEARCH_PERMISSION,)

#: FR-011. Set this when the vendor cannot be asked what a credential may do, so
#: the probe is the cheapest form of the read the capability itself makes.
#: Leave it empty when the vendor has a real introspection endpoint.
_FALLBACK_NOTE: Final = (
    "TODO: whether this vendor can introspect a permission. If it cannot, say so here "
    "and the report will carry it; if it can, use the introspection call and clear this."
)


@dataclass(frozen=True, slots=True)
class {verifier_class}:
    """Checks a stored {title} credential end to end, and what it may do."""

    integration: str = INTEGRATION
    region: str = ""

    @property
    def probe_description(self) -> str:
        """Return what call proves connectivity, and why that call."""
        return (
            "TODO: name the call and say why it is the right probe — cheapest, read-only, "
            "and requiring no permission beyond authentication if the vendor has one"
        )

    def probes(self) -> tuple[PermissionProbe, ...]:
        """Return one probe per permission this integration's capabilities need."""
        return (
            client_probe(
                SEARCH_PERMISSION,
                build=self._client,
                call=lambda client: client.search("*", start="", end="", limit=1),
                fallback_note=_FALLBACK_NOTE,
            ),
        )

    async def connect(self, transport: object, context: object) -> Connectivity:
        """Return whether {title} accepted this team's credential."""
        if not isinstance(transport, ProxyTransport) or not isinstance(context, RequestContext):
            return Connectivity(
                reachable=False,
                detail="the verifier needs a proxy transport and a request context",
            )
        try:
            response = await self._client(transport, context).ping()
        except IntegrationError as error:
            return Connectivity(
                reachable=False,
                detail=_ADVICE.get(error.reason, str(error)),
                status_code=error.status_code,
            )
        return Connectivity(
            reachable=True,
            detail="{title} accepted the credential.",
            status_code=response.status_code,
        )

    async def probe(self, transport: object, context: object) -> VerificationResult:
        """Return what {title} said when this team's credential was used."""
        connectivity = await self.connect(transport, context)
        return VerificationResult(
            integration=self.integration,
            ok=connectivity.reachable,
            detail=connectivity.detail,
            status_code=connectivity.status_code,
        )

    def _client(self, transport: object, context: object) -> {client_class}:
        """Return a client for one probe. It holds no credential; the proxy injects one."""
        if not isinstance(transport, ProxyTransport) or not isinstance(context, RequestContext):
            raise TypeError("a {integration} probe needs a proxy transport and a request context")
        return {client_class}(transport=transport, context=context, region=self.region)


__all__ = [
    "PERMISSIONS",
    "SEARCH_PERMISSION",
    "{verifier_class}",
]
'''

TOOLS_PACKAGE_TEMPLATE = '''"""{title}'s agent-callable capabilities.

{provenance}

Discovery walks this package, so adding a capability here is one module and no
edit anywhere else. Keep the set small: the model reads every declaration in the
catalogue on every turn, and a vendor contributing eight tools where two would
do costs that on every incident, including the ones this vendor is irrelevant to.
"""

from __future__ import annotations

from integrations.{integration}.tools.log_statistics import {integration}_log_statistics

__all__ = [
    "{integration}_log_statistics",
]
'''

TOOL_TEMPLATE = '''"""TODO: one line on what this reads and what it is for.

{provenance}

TODO: a paragraph on why this capability exists in the shape it does — what an
investigation asks it, what it deliberately does not return, and what the
alternative was.

Source of truth: TODO — the vendor endpoint this reflects, so a future reader can
check the mapping when the upstream changes.
"""

from __future__ import annotations

from typing import Any

from core.capability.decorator import tool
from core.capability.metadata import EvidenceType, Requirements, SideEffectLevel
from core.capability.result import CapabilityResult, Evidence
from integrations._base.access import current
from integrations._base.capability import unconfigured, vendor_failure
from integrations._base.errors import IntegrationError
from integrations.{integration}.client import {client_class}
from integrations.{integration}.schema import INTEGRATION

TOOL_NAME = "{integration}_log_statistics"

#: How many records one call returns. Small on purpose: the model reads this,
#: and a hundred records buys nothing the tenth did not already say.
DEFAULT_LIMIT = 20

_USE_CASES = (
    "TODO: a situation where this is the right call, phrased the way an alert would be",
    "TODO: a second one",
)

# Anti-examples suppress this capability when they describe the incident. They
# are the highest-value field here and the one most often left empty: without
# them the tool competes for a slot on every incident that shares a tag.
_ANTI_EXAMPLES = (
    "TODO: a situation where this looks relevant and is not",
)


@tool(
    name=TOOL_NAME,
    display_name="{title} log statistics",
    description=(
        "TODO: what it returns and when to reach for it, in two or three sentences. This "
        "is what the model reads when choosing, so write it for that reader rather than "
        "for a contributor reading the source."
    ),
    domain="{domain}",
    evidence_source=INTEGRATION,
    evidence_type=EvidenceType.LOG,
    # No default exists for this, structurally. Choose deliberately: read,
    # read_sensitive, write_reversible, write_irreversible, destructive.
    # read_sensitive is right whenever the result can carry what a user typed —
    # log bodies almost always can. Anything above it also needs
    # requires_approval, approval_reason, a rollback plan, and a risk_class.
    side_effect_level=SideEffectLevel.READ,
    parallel_safe=True,
    requires=Requirements(integrations=(INTEGRATION,)),
    tags=("{domain}", "{integration}"),
    use_cases=_USE_CASES,
    anti_examples=_ANTI_EXAMPLES,
)
async def {integration}_log_statistics(
    query: str,
    start: str,
    end: str,
    limit: int = DEFAULT_LIMIT,
) -> CapabilityResult:
    """TODO: what this returns, not how it works."""
    access = current()
    if access is None:
        return unconfigured(TOOL_NAME, INTEGRATION)

    client = access.client({client_class}, capability=TOOL_NAME)
    try:
        found = await client.search(query, start=start, end=end, limit=min(limit, DEFAULT_LIMIT))
    except IntegrationError as error:
        return vendor_failure(TOOL_NAME, error)

    records: list[dict[str, Any]] = [dict(record) for record in found.items]
    return CapabilityResult.ok(
        TOOL_NAME,
        value={{"query": query, "start": start, "end": end, "records": records}},
        truncated=found.truncated,
        evidence=(
            Evidence(
                source=INTEGRATION,
                evidence_type=EvidenceType.LOG,
                summary=(
                    f"{{len(records)}} record(s) matching {{query!r}}"
                    + (", and more matched than were read" if found.truncated else "")
                ),
                reference=f"{integration}:search:{{query}}@{{start}}..{{end}}",
            ),
        ),
    )
'''

DOCS_TEMPLATE = """# {title}

TODO: one paragraph on what this integration reads and what an investigation
asks it for.

## Setup

| Field | Where it comes from | Secret |
|---|---|---|
| `token` | TODO: the exact place in this vendor's console | yes |
| `region` | TODO: which regional deployment | no |

```bash
ninjasre integrations setup {integration}
ninjasre integrations verify {integration}
```

The prompt asks for each field the schema declares and writes the values
straight to the vault. Nothing is displayed back, and nothing reaches the agent:
a capability carries a handle and the credential proxy injects the real value at
the network edge.

## Permissions

TODO: one row per permission the capabilities need, named as this vendor names
it, with what stops working without it.

| Permission | What it grants | Without it |
|---|---|---|
| TODO | TODO | TODO |

TODO: say whether this vendor can be asked what a credential may do. If it
cannot, say which read each permission is probed by instead — the person reading
a verification result needs to know a permission was inferred rather than
reported.

## Limitations

TODO: the things that will surprise somebody at 03:00. Retention windows,
sampling above a volume threshold, rate limits and whose they are, what the
integration deliberately does not do, and anything the vendor's own
documentation understates.
"""

SCENARIO_TEMPLATE = '''"""{title}, end to end: capability, client, proxy, injection, vendor.

{provenance}

The seventh parity artefact, and the one whose absence is hardest to notice. An
integration with everything else looks finished; what it lacks is anything that
would fail when the vendor changes a response shape. This drives the whole path
with nothing mocked between the tool and the wire, so a renamed field or a
changed cursor fails in the build rather than in an incident.
"""

from __future__ import annotations

from typing import Final

from tests.synthetic.integration_scenarios import IntegrationScenario, json_response

#: TODO: a credential in the shape this vendor's schema requires. Not a real
#: one — the suite asserts that none of these values reaches a client.
CREDENTIAL: Final[dict[str, str]] = {{"token": "scenario-token-{integration}"}}

SEARCH: Final = IntegrationScenario(
    key="{integration}-search",
    integration="{integration}",
    capability="{integration}_log_statistics",
    arguments={{"query": "service:checkout", "start": "now-1h", "end": "now", "limit": 5}},
    responses=(
        # TODO: the vendor's own response shape, copied from a real one with the
        # values changed. The point of this scenario is that a change to that
        # shape fails here.
        json_response({{"results": [{{"id": "1"}}], "next_cursor": None}}),
    ),
    credential=CREDENTIAL,
    expected_summary="1 record(s) matching",
)

SCENARIOS: Final[tuple[IntegrationScenario, ...]] = (SEARCH,)

__all__ = ["CREDENTIAL", "SCENARIOS", "SEARCH"]
'''


def _titled(name: str) -> str:
    """Return ``name`` as a human-readable display name."""
    return name.replace("_", " ").title()


def _class_prefix(name: str) -> str:
    """Return ``name`` as a class-name prefix."""
    return "".join(part.capitalize() for part in name.split("_"))


def _write(path: Path, text: str) -> None:
    """Write ``text`` to ``path``, creating the directories above it."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def _skill_from_template(repo_root: Path, integration: str, domain: str) -> str:
    """Return the domain template with the vendor substituted in (FR-018)."""
    source = repo_root.joinpath(*_TEMPLATE_ROOT_PARTS, template_for(domain), "SKILL.md")
    return source.read_text(encoding="utf-8").replace(PLACEHOLDER, integration)


def scaffold_integration(
    repo_root: Path,
    integration: str,
    *,
    domain: str,
    dry_run: bool = False,
) -> list[Path]:
    """Create the integration's seven artefacts and return the paths written."""
    plan = validate(repo_root, integration, domain)
    written = list(plan.paths())
    if dry_run:
        return written

    fields = {
        "integration": integration,
        "title": _titled(integration),
        "domain": domain,
        "category": _CATEGORY_MEMBERS[domain],
        "client_class": f"{_class_prefix(integration)}Client",
        "verifier_class": f"{_class_prefix(integration)}Verifier",
        "provenance": _PROVENANCE,
    }

    _write(plan.schema, SCHEMA_TEMPLATE.format(**fields))
    _write(plan.client, CLIENT_TEMPLATE.format(**fields))
    _write(plan.verifier, VERIFIER_TEMPLATE.format(**fields))
    _write(plan.tools_package / "__init__.py", TOOLS_PACKAGE_TEMPLATE.format(**fields))
    _write(plan.tool_module, TOOL_TEMPLATE.format(**fields))
    _write(plan.package / "__init__.py", PACKAGE_TEMPLATE.format(**fields))
    _write(plan.docs, DOCS_TEMPLATE.format(**fields))
    _write(plan.skill, _skill_from_template(repo_root, integration, domain))
    _write(plan.scenario, SCENARIO_TEMPLATE.format(**fields))

    return written


def remaining_work(integration: str) -> list[str]:
    """Return the parts a scaffold deliberately cannot write."""
    return [
        "Choose the side-effect level deliberately. It has no default, and anything "
        "above read_sensitive needs an approval reason and a rollback plan. A capability "
        "whose result can carry what a user typed is read_sensitive.",
        "Write the permission list in verifier.py, named as the vendor names each one. "
        "A guessed permission is worse than a missing one: the verifier would report "
        "success for a credential that cannot do the job.",
        "Say whether the vendor can be asked what a credential may do. If it cannot, "
        "each probe is the cheapest read the capability itself makes, and the fallback "
        "note is what tells the operator the permission was inferred.",
        "Replace the region map with the vendor's real hosts. Exact names, no wildcards "
        "— it is also the egress allow-list.",
        "Check the pagination style against the vendor's documentation. Cursor and "
        "page-token end on an absent token; offset ends on a short page and must "
        "declare its page size.",
        "Write the anti-examples. Nothing fails without them; selection just gets "
        "worse, on every incident, until somebody notices.",
        "Replace the scenario's scripted response with the vendor's real shape. That "
        "is what makes a future change to it fail here rather than at 03:00.",
        f"Run `make verify` — the parity check, the contract suite, and the skill "
        f"binding all cover {integration} from the moment it exists.",
    ]


def main(argv: Sequence[str] | None = None) -> int:
    """Create an integration and print what still has to be written by hand."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("integration", help="the vendor name, lowercase with underscores")
    parser.add_argument(
        "--domain",
        required=True,
        help="the methodology domain this vendor's skill starts from",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="report what would be written without writing it"
    )
    arguments = parser.parse_args(argv)

    try:
        written = scaffold_integration(
            REPO_ROOT,
            arguments.integration,
            domain=arguments.domain,
            dry_run=arguments.dry_run,
        )
    except ScaffoldError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    verb = "would write" if arguments.dry_run else "wrote"
    for path in written:
        print(f"{verb} {path.relative_to(REPO_ROOT)}")

    if arguments.dry_run:
        return 0

    print("\nNo existing file was edited — discovery finds this on the next build.")
    print("Before it is worth shipping:")
    for index, step in enumerate(remaining_work(arguments.integration), 1):
        print(f"  {index}. {step}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
