"""Create the data platform schema.

Every table feature 006 declares, in one revision, because before this there was
no schema to migrate from. Generated by ``alembic revision --autogenerate``
against the models and kept as the generated output — a hand-written initial
revision is a second description of the schema, and the two disagree the first
time somebody edits only one.

The ``downgrade`` drops everything in dependency order, which is what makes
SC-008's forward-and-back test possible against a seeded database.

Two kinds of table are deliberately absent, and ``env.py``'s ``include_object``
is what keeps them out: Apache AGE's own catalogue, which the extension owns,
and the per-generation ``ninjasre_vec_*`` tables, whose width depends on the
embedding model in use and which are therefore data rather than schema.

Revision: 0001_initial
Parent: none
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from platform.persistence.postgres.crypto import EncryptedSecret

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organisations",
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("org_id"),
    )
    op.create_table(
        "agent_runs",
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("trigger", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("alert_id", sa.String(length=128), nullable=True),
        sa.Column("runtime", sa.String(length=256), nullable=True),
        sa.Column("model_id", sa.String(length=256), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("run_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organisations.org_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("org_id", "run_id"),
    )
    op.create_index("ix_agent_runs_alert", "agent_runs", ["org_id", "alert_id"], unique=False)
    op.create_index("ix_agent_runs_started", "agent_runs", ["org_id", "started_at"], unique=False)
    op.create_index("ix_agent_runs_status", "agent_runs", ["org_id", "status"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("approval_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=256), nullable=False),
        sa.Column("side_effect_level", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.String(length=128), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["org_id"], ["organisations.org_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("org_id", "approval_id"),
    )
    op.create_index("ix_approvals_run", "approvals", ["org_id", "run_id"], unique=False)
    op.create_index(
        "ix_approvals_state", "approvals", ["org_id", "state", "requested_at"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_kind", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=256), nullable=False),
        sa.Column("resource_kind", sa.String(length=256), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organisations.org_id"],
        ),
        sa.PrimaryKeyConstraint("org_id", "event_id"),
    )
    op.create_index("ix_audit_events_actor", "audit_events", ["org_id", "actor_id"], unique=False)
    op.create_index(
        "ix_audit_events_resource",
        "audit_events",
        ["org_id", "resource_kind", "resource_id"],
        unique=False,
    )
    op.create_index("ix_audit_events_time", "audit_events", ["org_id", "occurred_at"], unique=False)
    op.create_table(
        "config_nodes",
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("node_id", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("parent_id", sa.String(length=128), nullable=True),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id", "parent_id"],
            ["config_nodes.org_id", "config_nodes.node_id"],
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organisations.org_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("org_id", "node_id"),
    )
    op.create_index("ix_config_nodes_parent", "config_nodes", ["org_id", "parent_id"], unique=False)
    op.create_table(
        "credentials",
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("handle", sa.String(length=128), nullable=False),
        sa.Column("integration", sa.String(length=256), nullable=False),
        sa.Column("secret", EncryptedSecret(), nullable=False),
        sa.Column("key_version", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("labels", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["org_id"], ["organisations.org_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("org_id", "handle"),
    )
    op.create_index(
        "ix_credentials_integration", "credentials", ["org_id", "integration"], unique=False
    )
    op.create_table(
        "episodes",
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("episode_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("signature", sa.String(length=256), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("components", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("episode_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organisations.org_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("org_id", "episode_id"),
    )
    op.create_index(
        "ix_episodes_components", "episodes", ["components"], unique=False, postgresql_using="gin"
    )
    op.create_index("ix_episodes_occurred", "episodes", ["org_id", "occurred_at"], unique=False)
    op.create_index("ix_episodes_run", "episodes", ["org_id", "run_id"], unique=False)
    op.create_index(
        "ix_episodes_signature", "episodes", ["org_id", "signature", "occurred_at"], unique=False
    )
    op.create_table(
        "knowledge_documents",
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("document_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("checksum", sa.String(length=256), nullable=False),
        sa.Column("source_uri", sa.Text(), nullable=True),
        sa.Column("content_type", sa.String(length=256), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("document_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organisations.org_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("org_id", "document_id"),
    )
    op.create_index(
        "ix_knowledge_documents_updated",
        "knowledge_documents",
        ["org_id", "updated_at"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_documents_uri", "knowledge_documents", ["org_id", "source_uri"], unique=False
    )
    op.create_table(
        "scheduled_jobs",
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("job_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("kind", sa.String(length=256), nullable=False),
        sa.Column("schedule", sa.String(length=256), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_outcome", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["org_id"], ["organisations.org_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("org_id", "job_id"),
    )
    op.create_index(
        "ix_scheduled_jobs_due", "scheduled_jobs", ["enabled", "next_run_at"], unique=False
    )
    op.create_index("ix_scheduled_jobs_kind", "scheduled_jobs", ["org_id", "kind"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["org_id"], ["organisations.org_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("org_id", "session_id"),
    )
    op.create_index(
        "ix_sessions_status", "sessions", ["org_id", "status", "updated_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("email_folded", sa.String(length=256), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("external_subject", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["org_id"], ["organisations.org_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("org_id", "user_id"),
    )
    op.create_index("ix_users_email", "users", ["org_id", "email_folded"], unique=True)
    op.create_index("ix_users_subject", "users", ["org_id", "external_subject"], unique=False)
    op.create_table(
        "vector_indexes",
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("namespace", sa.String(length=128), nullable=False),
        sa.Column("active_generation", sa.Integer(), nullable=False),
        sa.Column("m", sa.Integer(), nullable=False),
        sa.Column("ef_construction", sa.Integer(), nullable=False),
        sa.Column("ef_search", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["org_id"], ["organisations.org_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("org_id", "namespace"),
    )
    op.create_table(
        "api_tokens",
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("token_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("token_hash", sa.String(length=256), nullable=False),
        sa.Column("scopes", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id", "user_id"], ["users.org_id", "users.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("org_id", "token_id"),
        sa.UniqueConstraint("token_hash", name="uq_api_tokens_hash"),
    )
    op.create_index("ix_api_tokens_user", "api_tokens", ["org_id", "user_id"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("evidence_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("source", sa.String(length=256), nullable=False),
        sa.Column("evidence_type", sa.String(length=256), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cited", sa.Boolean(), nullable=False),
        sa.Column("recorded_seq", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id", "run_id"], ["agent_runs.org_id", "agent_runs.run_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("org_id", "evidence_id"),
    )
    op.create_index("ix_evidence_run", "evidence", ["org_id", "run_id"], unique=False)
    op.create_index("ix_evidence_source", "evidence", ["org_id", "source"], unique=False)
    op.create_table(
        "job_claims",
        sa.Column("claim_id", sa.String(length=128), nullable=False),
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("job_id", sa.String(length=128), nullable=False),
        sa.Column("worker_id", sa.String(length=128), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id", "job_id"],
            ["scheduled_jobs.org_id", "scheduled_jobs.job_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("claim_id"),
        sa.UniqueConstraint("org_id", "job_id", name="uq_job_claims_job"),
    )
    op.create_index("ix_job_claims_lease", "job_claims", ["lease_expires_at"], unique=False)
    op.create_table(
        "knowledge_chunks",
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("chunk_id", sa.String(length=128), nullable=False),
        sa.Column("document_id", sa.String(length=128), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("chunk_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id", "document_id"],
            ["knowledge_documents.org_id", "knowledge_documents.document_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("org_id", "chunk_id"),
    )
    op.create_index(
        "ix_knowledge_chunks_document",
        "knowledge_chunks",
        ["org_id", "document_id", "ordinal"],
        unique=False,
    )
    op.create_table(
        "role_bindings",
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("binding_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=256), nullable=False),
        sa.Column("node_id", sa.String(length=128), nullable=True),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id", "user_id"], ["users.org_id", "users.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("org_id", "binding_id"),
    )
    op.create_index("ix_role_bindings_user", "role_bindings", ["org_id", "user_id"], unique=False)
    op.create_table(
        "rollback_plans",
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("approval_id", sa.String(length=128), nullable=False),
        sa.Column("plan_id", sa.String(length=128), nullable=False),
        sa.Column("steps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("executed_steps", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id", "approval_id"],
            ["approvals.org_id", "approvals.approval_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("org_id", "approval_id"),
        sa.UniqueConstraint("org_id", "plan_id", name="uq_rollback_plans_plan"),
    )
    op.create_table(
        "run_turns",
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("turn_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id", "run_id"], ["agent_runs.org_id", "agent_runs.run_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("org_id", "turn_id"),
    )
    op.create_index("ix_run_turns_run", "run_turns", ["org_id", "run_id", "index"], unique=False)
    op.create_table(
        "tool_calls",
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("call_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("turn_id", sa.String(length=128), nullable=False),
        sa.Column("tool_name", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("evidence_ids", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("recorded_seq", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id", "run_id"], ["agent_runs.org_id", "agent_runs.run_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("org_id", "call_id"),
    )
    op.create_index("ix_tool_calls_name", "tool_calls", ["org_id", "tool_name"], unique=False)
    op.create_index("ix_tool_calls_run", "tool_calls", ["org_id", "run_id"], unique=False)
    op.create_table(
        "vector_generations",
        sa.Column("org_id", sa.String(length=128), nullable=False),
        sa.Column("namespace", sa.String(length=128), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=256), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("table_name", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id", "namespace"],
            ["vector_indexes.org_id", "vector_indexes.namespace"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("org_id", "namespace", "generation"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the change.

    Every migration has one, and it is tested. A schema change that cannot be
    rolled back turns a bad release into an outage with no way back.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vector_generations")
    op.drop_index("ix_tool_calls_run", table_name="tool_calls")
    op.drop_index("ix_tool_calls_name", table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_index("ix_run_turns_run", table_name="run_turns")
    op.drop_table("run_turns")
    op.drop_table("rollback_plans")
    op.drop_index("ix_role_bindings_user", table_name="role_bindings")
    op.drop_table("role_bindings")
    op.drop_index("ix_knowledge_chunks_document", table_name="knowledge_chunks")
    op.drop_table("knowledge_chunks")
    op.drop_index("ix_job_claims_lease", table_name="job_claims")
    op.drop_table("job_claims")
    op.drop_index("ix_evidence_source", table_name="evidence")
    op.drop_index("ix_evidence_run", table_name="evidence")
    op.drop_table("evidence")
    op.drop_index("ix_api_tokens_user", table_name="api_tokens")
    op.drop_table("api_tokens")
    op.drop_table("vector_indexes")
    op.drop_index("ix_users_subject", table_name="users")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_sessions_status", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("ix_scheduled_jobs_kind", table_name="scheduled_jobs")
    op.drop_index("ix_scheduled_jobs_due", table_name="scheduled_jobs")
    op.drop_table("scheduled_jobs")
    op.drop_index("ix_knowledge_documents_uri", table_name="knowledge_documents")
    op.drop_index("ix_knowledge_documents_updated", table_name="knowledge_documents")
    op.drop_table("knowledge_documents")
    op.drop_index("ix_episodes_signature", table_name="episodes")
    op.drop_index("ix_episodes_run", table_name="episodes")
    op.drop_index("ix_episodes_occurred", table_name="episodes")
    op.drop_index("ix_episodes_components", table_name="episodes", postgresql_using="gin")
    op.drop_table("episodes")
    op.drop_index("ix_credentials_integration", table_name="credentials")
    op.drop_table("credentials")
    op.drop_index("ix_config_nodes_parent", table_name="config_nodes")
    op.drop_table("config_nodes")
    op.drop_index("ix_audit_events_time", table_name="audit_events")
    op.drop_index("ix_audit_events_resource", table_name="audit_events")
    op.drop_index("ix_audit_events_actor", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_approvals_state", table_name="approvals")
    op.drop_index("ix_approvals_run", table_name="approvals")
    op.drop_table("approvals")
    op.drop_index("ix_agent_runs_status", table_name="agent_runs")
    op.drop_index("ix_agent_runs_started", table_name="agent_runs")
    op.drop_index("ix_agent_runs_alert", table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_table("organisations")
    # ### end Alembic commands ###
