name: Application pipeline

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: application-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    if: github.event_name == 'pull_request'
    uses: JustShinobi/platform-workflows/.github/workflows/verify.yml@1472c2963006f33d7b15768cf799560ce086aac8
    with:
      descriptor: .ci/application.yaml

  release:
    if: github.event_name != 'pull_request'
    uses: JustShinobi/platform-workflows/.github/workflows/application-release.yml@1472c2963006f33d7b15768cf799560ce086aac8
    with:
      descriptor: .ci/application.yaml
    secrets: inherit
